services:
- postgresql
before_script:
- psql -c 'create database mentorz_test;' -U postgres
language: ruby
rvm:
- 2.3.1
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake db:seed RAILS_ENV=test
- bundle exec rspec spec/
